config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"

  resources :flights, only: %i[index]
  resources :bookings, only: %i[new create show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"

  validates :code, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  scope :filter_by_date, ->(date) {
    where("start BETWEEN ? AND ?",
      date.to_date.beginning_of_day, date.to_date.end_of_day)
      .order(:start)
  }
  scope :filter_by_departure_code, ->(departure_code) {
    joins(:departure_airport).where(departure_airport: {code: departure_code})
  }
  scope :filter_by_arrival_code, ->(arrival_code) {
    joins(:arrival_airport).where(arrival_airport: {code: arrival_code})
  }

  scope :departure_codes,
    -> { joins(:departure_airport).distinct.order(:code).pluck(:code) }
  scope :arrival_codes,
    -> { joins(:arrival_airport).distinct.order(:code).pluck(:code) }
  scope :distinct_depart_dates,
    -> {
      distinct.order(:start).pluck(:start).map do |start_datetime|
        start_datetime.strftime("%F")
      end.uniq
    }

  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
  belongs_to :departure_airport, class_name: "Airport",
    inverse_of: "departing_flights"
  belongs_to :arrival_airport, class_name: "Airport",
    inverse_of: "arriving_flights"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])

    @booking = Booking.new(flight_id: params[:flight_id])

    @num_tickets = params[:num_tickets].to_i
    @num_tickets.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer
          .with(booking: @booking, passenger:)
          .confirmation_email.deliver_later
      end

      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all

    if params[:search].present?
      @matching_flights = Flight.filter_by_date(params[:search][:date])
        .filter_by_arrival_code(params[:search][:arrival_code])
        .filter_by_departure_code(params[:search][:departure_code])
    end
    # if turbo_frame_request?
    #   render partial: "matching_flights", locals: {matching_flights: @matching_flights}
    # else
    #   render :index
    # end
  end

  def show
    @flight = Flight.find(params[:id])
  end

  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.new(flight_params)

    if @flight.save
      redirect_to @flight
    else
      render "new"
    end
  end

  private

  def flight_params
    params.require(:flight)
      .permit(:departure_airport_id, :arrival_airport_id, :start, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h2>Create Booking</h2>

<%= "Flight #{@flight.id} details:" %>
<%= render partial: "flights/flight", locals: {flight: @flight}%>
<%= form_with model: @booking do |form| %>
  <%= form.hidden_field :flight_id, value: @flight.id %>
  <ul data-controller="dynamic-form">
    <%= form.fields_for :passengers, child_index: "RECORD_INDEX" do |passengers_form| %>
      <template data-dynamic-form-target="template">
        <li>
          <%= passengers_form.label :name %>
          <%= passengers_form.text_field :name %>

          <%= passengers_form.label :email %>
          <%= passengers_form.email_field :email %>

          <button type="button" data-action="dynamic-form#remove">Remove Passenger</button>
        </li>
      </template>
    <% end %>
    <%= form.fields_for :passengers do |passengers_form| %>
      <li>
        <%= passengers_form.label :name %>
        <%= passengers_form.text_field :name %>

        <%= passengers_form.label :email %>
        <%= passengers_form.email_field :email %>


        <button type="button" data-action="dynamic-form#remove">Remove Passenger</button>
      </li>
    <% end %>
    <div data-dynamic-form-target="target"></div>
    <button type="button" data-action="dynamic-form#add">Add Passenger</button>
  </ul>
  <%= form.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking</h1>
<%= render partial: "flights/flight", locals: {flight: @flight} %>

<h2>Passengers:</h2>
<ol>
  <% @booking.passengers.each do |passenger| %>
    <li>
      <%= passenger.name %>
      <%= passenger.email %>
    </li>
  <% end %>
</ol>

app/views/flights/_flight.html.erb
<ul class="flight-details">
  <li>Depart: <%= flight.departure_airport.code %></li>
  <li>Arrive: <%= flight.arrival_airport.code %></li>
  <li>Date: <%= flight.start.strftime("%F") %></li>
  <li>Departs at: <%= flight.start.strftime("%I:%M%p") %></li>
  <li>Duration: <%= flight.duration.inspect %></li>
</ul>

app/views/flights/_matching_flights.html.erb
<% unless matching_flights.nil?  %>
  <%= "No matching flights" if matching_flights.empty? %>

  <%= form_with url: new_booking_path, method: :get do |form| %>
    <ul class="matching-flights">
      <% matching_flights.each do |flight| %>
        <li class="flight">
          <%= form.radio_button :flight_id, flight.id %>
          <%= form.label :flight_id, "Flight #{flight.id} details:" %>
          <%= render partial: "flight", locals: {flight: flight}%>
        </li>
      <% end %>
    </ul>
    <%= form.hidden_field :num_tickets, value: params[:num_tickets] %>
    <%= form.submit "Select" %>
  <% end %>
<% end %>

app/views/flights/index.html.erb
<%= form_with url: flights_path, method: :get,
  data: {turbo_frame: "matching_flights",
         turbo_action: "advance"} do |form| %>
  <%= form.fields_for :search do |search_form| %>
    <div>
      <%= search_form.label :departure_code %>
      <% departure_code = params[:search].nil? ? "" : params[:search][:departure_code] %>
      <%= search_form.select :departure_code, @flights.departure_codes, 
                                              selected: departure_code %>
    </div>
    <div>
      <%= search_form.label :arrival_code %>
      <% arrival_code = params[:search].nil? ? "" : params[:search][:arrival_code] %>
      <%= search_form.select :arrival_code, @flights.arrival_codes,
                                            selected: arrival_code %>
    </div>
    <div>
      <%= search_form.label :date %>
      <% date = params[:search].nil? ? "" : params[:search][:date] %>
      <%= search_form.select :date, @flights.distinct_depart_dates,
                                    selected: date %>
    </div>
  <% end %>
  <div>
    <%= form.label :num_tickets %>
    <%= form.select :num_tickets, (1..4).to_a %>
  </div>
  <%= form.submit "Search" %>
<% end %>

<div>
  <%= render "matching_flights", matching_flights: @matching_flights %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>